### ISSUE TITLE
Number of Samples Exception

### ISSUE THREAD

**Issue by SoftwareentwicklungHell** [rajshah4/image_keras#3]
Hey, 

first thanks for your try to get a ThensoFlow version running. 

In step two everything works fine till I come to the fitting:

`line 137, in <module>
    validation_data=(validation_data, validation_labels))
`

`ValueError: Input arrays should have the same number of samples as target arrays. Found 65536 input samples and 2048 target samples.`

Do you have any idea what the problem could be? I have two categories (not cats and dogs) with exactly the same length than your data (1024 per category and for validation 416 images)

Only difference may be that I'm using Keras 2.0.2, but I hope that this is not the problem. 

Any idea?

Thanks
Florian

**Comment by SoftwareentwicklungHell** [comment]
Really no idea where he gets its 65536 input samples from. My train folder just contains 2048 images but checkin 

`train_data = np.load(open('models/bottleneck_features_train.npy', 'rb'))
print(len(train_data))`

really gives the number of 65536.

**Comment by rajshah4** [comment]
Hmm, something is not right, if you get a length of 65536 that means there is some error happening.  Are you running the notebook (versus the notebook_extras)?  Can you give me a better idea of how far you have gotten and what works . . .  by section  . . . not sure what line number 137 is.

**Comment by SoftwareentwicklungHell** [comment]
Thanks for your reply, this is my code, but because of some reformatting it is line 128:

`import os
import numpy as np
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D
from keras import optimizers
from keras import backend as K
import h5py

K.set_image_dim_ordering('tf')

img_width, img_height = 150, 150

train_data_dir = 'forbidden_images/train'
validation_data_dir = 'forbidden_images/validation'

nb_epoch = 30
nb_train_samples = 2048
nb_validation_samples = 832

datagen = ImageDataGenerator(rescale=1./255)

model_vgg = Sequential()
model_vgg.add(ZeroPadding2D((1, 1), input_shape=(img_width, img_height,3)))
model_vgg.add(Conv2D(64, 3, 3, activation='relu', name='conv1_1'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(64, 3, 3, activation='relu', name='conv1_2'))
model_vgg.add(MaxPooling2D((2, 2), strides=(2, 2)))

model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(128, 3, 3, activation='relu', name='conv2_1'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(128, 3, 3, activation='relu', name='conv2_2'))
model_vgg.add(MaxPooling2D((2, 2), strides=(2, 2)))

model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(256, 3, 3, activation='relu', name='conv3_1'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(256, 3, 3, activation='relu', name='conv3_2'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(256, 3, 3, activation='relu', name='conv3_3'))
model_vgg.add(MaxPooling2D((2, 2), strides=(2, 2)))

model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(512, 3, 3, activation='relu', name='conv4_1'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(512, 3, 3, activation='relu', name='conv4_2'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(512, 3, 3, activation='relu', name='conv4_3'))
model_vgg.add(MaxPooling2D((2, 2), strides=(2, 2)))

model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(512, 3, 3, activation='relu', name='conv5_1'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(512, 3, 3, activation='relu', name='conv5_2'))
model_vgg.add(ZeroPadding2D((1, 1)))
model_vgg.add(Conv2D(512, 3, 3, activation='relu', name='conv5_3'))
model_vgg.add(MaxPooling2D((2, 2), strides=(2, 2)))

print('Model build')

f = h5py.File('models/vgg/vgg16_weights.h5')
for k in range(f.attrs['nb_layers']):
    if k >= len(model_vgg.layers) - 1:
    g = f['layer_{}'.format(k)]
    weights = [g['param_{}'.format(p)] for p in range(g.attrs['nb_params'])]
    layer = model_vgg.layers[k]

    if layer.__class__.__name__ in ['Convolution1D', 'Conv2D', 'Convolution3D', 'AtrousConv2D']:
        weights[0] = np.transpose(weights[0], (2, 3, 1, 0))

    layer.set_weights(weights)

f.close()

print('VGG 16 Weights added')

print('Create train_generator_bottleneck')
train_generator_bottleneck = datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=32,
        class_mode=None,
        shuffle=False)

print('Create validation_generator_bottleneck')
validation_generator_bottleneck = datagen.flow_from_directory(
        validation_data_dir,
        target_size=(img_width, img_height),
        batch_size=32,
        class_mode=None,
        shuffle=False)
        
print('Create bottleneck_features_train')   
bottleneck_features_train = model_vgg.predict_generator(train_generator_bottleneck, nb_train_samples)
np.save(open('models/bottleneck_features_train.npy', 'wb'), bottleneck_features_train)

print('Create bottleneck_features_validation')
bottleneck_features_validation = model_vgg.predict_generator(validation_generator_bottleneck, nb_validation_samples)
np.save(open('models/bottleneck_features_validation.npy', 'wb'), bottleneck_features_validation)

print('Start train data')
train_data = np.load(open('models/bottleneck_features_train.npy', 'rb'))
train_labels = np.array([0] * (nb_train_samples // 2) + [1] * (nb_train_samples // 2))

print('Start validation data')
validation_data = np.load(open('models/bottleneck_features_validation.npy', 'rb'))
validation_labels = np.array([0] * (nb_validation_samples // 2) + [1] * (nb_validation_samples // 2))

print('Create top model')
model_top = Sequential()
model_top.add(Flatten(input_shape=train_data.shape[1:]))
model_top.add(Dense(256, activation='relu'))
model_top.add(Dropout(0.5))
model_top.add(Dense(1, activation='sigmoid'))

model_top.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

nb_epoch=40
print('Start fitting')
model_top.fit(train_data, train_labels,
          epochs=nb_epoch, batch_size=32,
          validation_data=(validation_data, validation_labels))
          
model_top.save_weights('models/bottleneck_40_epochs.h5')

model_top.evaluate(validation_data, validation_labels)`

**Comment by SoftwareentwicklungHell** [comment]
When I hard code the label length to the given it runs fine to the end. 

But I'm not able to predict an test image, no matter what I try. It is the same as with the other version from the main blog entry. 

That is one of those errors (I know, looks like a theano/tensorflow problem, but I'm using tensor flow in all ways. 

`ValueError: Layer weight shape (3, 3, 3, 64) not compatible with provided weight shape (64, 3, 3, 3)`

**Comment by SoftwareentwicklungHell** [comment]
It is very frustrating that no example of keras image classification is working. I'll try training on my Debian server instead of OS X, may that will give a change. 

Additionally I have to say, I'm training for images and categories that are not available in VGG16 Imagenet set, may that could also be one of the problems.

**Comment by rajshah4** [comment]
Ok, lot going on.  I assume if you run the notebook as is, you are able to build a model just fine with the cat/dog training set.  Is that right?

The problems you are running into when you extend it to other data.  If you have images with two categories, you should be able to run the notebook just fine.  If you need more categories, you will have to tweak the code.  

Also, if you want to run a prediction on one image, I think I have code in the notebook extras that shows you how to do that.

**Comment by SoftwareentwicklungHell** [comment]
Well, I would try it with the notebook, but on my mac the provided docker image isn't running...always some problems ;)

It would be very helpful if you, not with the notebook, provide "ready to use" scripts for training the models, instead of doing some copy/paste work from the notebooks. 

Also a ready script for doing the prediction would be great.

**Comment by SoftwareentwicklungHell** [comment]
Ok, installed the docker image on my linux server and tested it with just a few images and it looks that with the notebook everything runs fine. 

It is really hard to get into keras if it decides to work in each environment completly different ;-)

**Comment by rajshah4** [comment]
That is great news and I know your frustration.  The promise of docker was that it was suppose to abstract away that OS layer and it doesn't always work right.  I am hoping now that you can spend your time runnings the scripts and doing some deep learning :)    Going to close out the issue
