### ISSUE TITLE
Tuple index out of range

### ISSUE THREAD

**Issue by NadineSf** [rajshah4/image_keras#4]
Dear Rajsh;

I am a beginner in Python and Machine Learning, thanks for your nice material and your last webinar, they helped me a lot.
In notebook_extras.ipynb, I tested the vizualization using Quiver, everything worked well expect 3 layers (flatten, fc1, fc2 and predictions).
When I am trying to pick the images from these 3 layers I am getting "for z in range(0, layer_outputs.shape[2]):IndexError: tuple index out of range"

Thanks
Nadine

**Comment by rajshah4** [comment]
Let me make sure i understand, the problem you have is when you are trying to examine your images using quiver?  Does the same problem affect the images I have included in the notebook?

**Comment by NadineSf** [comment]
Thank you for your reply. 
As you said, I am trying to examine my images using quiver and the same problem occurs using your notebook.

**Comment by NadineSf** [comment]
![image](https://cloud.githubusercontent.com/assets/23330881/25744372/474e8c4e-31a2-11e7-9c42-99250760f1c2.png)
![image](https://cloud.githubusercontent.com/assets/23330881/25744389/594b3d34-31a2-11e7-844b-ca6605d9a75c.png)
![image](https://cloud.githubusercontent.com/assets/23330881/25744391/5f8be1ee-31a2-11e7-805e-2961744081e0.png)
![image](https://cloud.githubusercontent.com/assets/23330881/25744395/66e103b6-31a2-11e7-99f5-052537fc4ccc.png)
![image](https://cloud.githubusercontent.com/assets/23330881/25744403/6d5860d6-31a2-11e7-9c5a-4e5d1f73818f.png)

**Comment by rajshah4** [comment]
Thanks Nadine, this is helpful.  Let me try and replicate it on my end.

**Comment by rajshah4** [comment]
I get the same behavior on my end.  My guess is that quiver doesn't support viewing the flatten or fully connected pieces (at least at this point).  Is still useful for seeing the layers.  To see whats going on with quiver, you can see their issues list over here: https://github.com/keplr-io/quiver/issues
Does this help?

**Comment by NadineSf** [comment]
Thank you for your reply. In my case it is useful to check the prediction layer too. 
I will check if it is possible to solve this issue.
The link is very useful thank you!
