### ISSUE TITLE
Wrong dimensions order

### ISSUE THREAD

**Issue by statist-bhfz** [rajshah4/image_keras#5]
Hi, 

Thank you for this tutorial. It was very helpful for me, but I have found one mistake:

```
input_shape = c(img_width, img_height, 3)
target_size = c(img_width, img_height)
```
should be
```
input_shape = c(img_height, img_width, 3)
target_size = c(img_height, img_width)
```

> channels_last corresponds to inputs with shape (batch, height, width, channels) while channels_first corresponds to inputs with shape (batch, channels, height, width).
https://rstudio.github.io/keras/reference/index.html

It doesn't matter for square images, but leads to wrong aspect ratio for non-square ones.

**Comment by rajshah4** [comment]
Thanks so much for catching this, I will update the code.  Feel free to do a pull request.

**Comment by rajshah4** [comment]
Thanks, I did update my code (but never tested with with a rectangular image).  Thanks for pointing this issue out.
